package cn.cbdi.cbsdmonitor.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.cbdi.cbsdmonitor.Bean.Employees;

import cn.cbdi.cbsdmonitor.greendao.EmployeesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig employeesDaoConfig;

    private final EmployeesDao employeesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        employeesDaoConfig = daoConfigMap.get(EmployeesDao.class).clone();
        employeesDaoConfig.initIdentityScope(type);

        employeesDao = new EmployeesDao(employeesDaoConfig, this);

        registerDao(Employees.class, employeesDao);
    }
    
    public void clear() {
        employeesDaoConfig.clearIdentityScope();
    }

    public EmployeesDao getEmployeesDao() {
        return employeesDao;
    }

}
